# ============================================
# FLASHCARDS - Cloud Build CI/CD
# ============================================
# Deploy automat la fiecare push pe GitHub
# Includes: Install → Test → Lint → Build → Deploy
# ============================================

steps:
  # ==========================================
  # Step 1: Install dependencies
  # ==========================================
  - name: 'node:20'
    entrypoint: npm
    args: ['ci', '--ignore-scripts']
    id: 'install'

  # ==========================================
  # Step 2: Run Tests FIRST (before typecheck to avoid race condition)
  # ==========================================
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'test']
    id: 'test'
    waitFor: ['install']

  # ==========================================
  # Step 3: Run TypeScript check (after tests complete)
  # ==========================================
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'typecheck']
    id: 'typecheck'
    waitFor: ['test']

  # ==========================================
  # Step 4: Run Linting (parallel with typecheck)
  # ==========================================
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'lint']
    id: 'lint'
    waitFor: ['install']

  # ==========================================
  # Step 5: Build Docker image
  # ==========================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:latest'
      - '.'
    id: 'build'
    waitFor: ['typecheck', 'lint', 'test']

  # ==========================================
  # Step 2: Push to Artifact Registry
  # ==========================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}'
    id: 'push'
    waitFor: ['build']

  # ==========================================
  # Step 3: Deploy to Cloud Run
  # ==========================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--add-cloudsql-instances'
      - '${PROJECT_ID}:${_REGION}:flashcards-db'
      - '--set-env-vars'
      - 'NODE_ENV=production,CORS_ORIGIN=*,DB_HOST=/cloudsql/${PROJECT_ID}:${_REGION}:flashcards-db,DB_PORT=5432,DB_NAME=flashcards,DB_USER=flashcards_user'
      - '--set-secrets'
      - 'DB_PASSWORD=flashcards-db-password:latest,JWT_ACCESS_SECRET=flashcards-jwt-access:latest,JWT_REFRESH_SECRET=flashcards-jwt-refresh:latest,GEMINI_API_KEY=flashcards-gem-key:latest'
    id: 'deploy'
    waitFor: ['push']

# ==========================================
# Substitution variables
# ==========================================
substitutions:
  _REGION: 'europe-west1'
  _REPOSITORY: 'flashcards'
  _IMAGE: 'flashcards-app'
  _SERVICE_NAME: 'flashcards'

# ==========================================
# Build options
# ==========================================
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  # Cache node_modules pentru build mai rapid
  volumes:
    - name: 'node_modules'
      path: '/workspace/node_modules'

# ==========================================
# Images to push
# ==========================================
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:latest'

# ==========================================
# Timeout (20 minutes)
# ==========================================
timeout: '1200s'
