# ============================================
# FLASHCARDS - Cloud Build CI/CD
# ============================================
# Deployment automat pe Google Cloud Run
# ============================================

steps:
  # ==========================================
  # Step 1: Build Docker image
  # ==========================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:latest'
      - '.'
    id: 'build'

  # ==========================================
  # Step 2: Push to Artifact Registry
  # ==========================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}'
    id: 'push'
    waitFor: ['build']

  # ==========================================
  # Step 3: Deploy to Cloud Run
  # ==========================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'DB_HOST=flashcards-db-host:latest,DB_PORT=flashcards-db-port:latest,DB_NAME=flashcards-db-name:latest,DB_USER=flashcards-db-user:latest,DB_PASSWORD=flashcards-db-password:latest,JWT_ACCESS_SECRET=flashcards-jwt-access:latest,JWT_REFRESH_SECRET=flashcards-jwt-refresh:latest,API_KEY=flashcards-gemini-key:latest'
    id: 'deploy'
    waitFor: ['push']

# ==========================================
# Substitution variables (can be overridden)
# ==========================================
substitutions:
  _REGION: 'europe-west1'
  _REPOSITORY: 'flashcards'
  _IMAGE: 'flashcards-app'
  _SERVICE_NAME: 'flashcards'

# ==========================================
# Build options
# ==========================================
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# ==========================================
# Images to push
# ==========================================
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE}:latest'

# ==========================================
# Timeout
# ==========================================
timeout: '1200s'
